implement feature create-user
Robinson-Dev/users pull request #13
Opened 2021-12-26 19:47 UTC by Robinson-Dev

2021-12-27 10:24 UTC, ClaudenirFreitas commented on pom.xml
> +											<minimum>0.9</minimum>
Cool. There are 2 unecessary dependencies, I believe we can remove them. 
- [dependency one](https://github.com/Robinson-Dev/users/pull/13/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R30):
- [dependency two](https://github.com/Robinson-Dev/users/pull/13/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8L36)

2021-12-27 11:07 UTC, ClaudenirFreitas requested changes

2021-12-27 11:07 UTC, ClaudenirFreitas commented on src/test/java/com/learning/users/UserTest.java
> +        user.setDateOfBirth(UtilPersonal.formattingDate("02-05-2000"));
We can use [LocalDate API](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html) instead of `UtilPersonal`.

2021-12-27 11:07 UTC, ClaudenirFreitas commented on pom.xml
> +											<minimum>0.9</minimum>
Cool. There are 2 unecessary dependencies, I believe we can remove them. 
- [dependency one](https://github.com/Robinson-Dev/users/pull/13/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R30): we can use [Java Bean Validation](https://javaee.github.io/tutorial/bean-validation002.html) for that if necessary.
- [dependency two](https://github.com/Robinson-Dev/users/pull/13/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8L36): we're using JUnit5.

2021-12-27 11:07 UTC, ClaudenirFreitas commented on src/main/java/utility/UtilPersonal.java
>  public class UtilPersonal {
There are some approaches to validate these kind of validation e.g LocaDate API, Java Bean Validation. 
Some authors said this is [an anti-pattern](https://lostechies.com/chrismissal/2009/06/01/anti-patterns-and-worst-practices-utils-class/), we can avoid that.

2021-12-27 11:07 UTC, ClaudenirFreitas commented on src/test/java/com/learning/users/UserTest.java
> +        user.setPhone(834185473);
I think `phone` attribute is a String, isn't it? We need to pass the DDI .e.g `+353 ...`.

2021-12-27 11:07 UTC, ClaudenirFreitas commented on src/test/java/com/learning/users/UserTest.java
> +        user.setGitHubProfile("Inserting data to simulate a gitHub profile. This will be integrated in the future");
We need to validate that this URL is valid too.

2021-12-27 11:07 UTC, ClaudenirFreitas commented on src/test/java/com/learning/users/UtilPersonalTest.java
> +                () -> Assertions.assertFalse(UtilPersonal.validateEmail("emailtest.com"))
`validateEmail` has not been used, correct? I didn't find references.

2021-12-27 11:07 UTC, ClaudenirFreitas commented on src/test/java/com/learning/users/UserRepositoryTest.java
>          userRepository.create(user);
Do we have a validation layer? E.g. is it possible to create an user without name?

2022-01-13 18:08 UTC, Robinson-Dev commented on src/test/java/com/learning/users/UserTest.java
> +        user.setDateOfBirth(UtilPersonal.formattingDate("02-05-2000"));
Changes were implemented using LocalDate API.

2022-01-13 18:10 UTC, Robinson-Dev commented on pom.xml
> +											<minimum>0.9</minimum>
Java Bean Validation was utilized as solution.

2022-01-13 18:14 UTC, Robinson-Dev commented on src/main/java/utility/UtilPersonal.java
>  public class UtilPersonal {
Also solved using Java Bean Validation, as proposed.

2022-01-13 18:15 UTC, Robinson-Dev commented on src/test/java/com/learning/users/UserTest.java
> +        user.setPhone(834185473);
You were right. Change was made to attend the field necessity.

2022-01-13 18:24 UTC, Robinson-Dev commented on src/test/java/com/learning/users/UserTest.java
> +        user.setGitHubProfile("Inserting data to simulate a gitHub profile. This will be integrated in the future");
In this situation I used Java Bean validation to verify if it is an URL. Will that be enough or should I be stricter about it?

2022-01-13 18:25 UTC, Robinson-Dev commented on src/test/java/com/learning/users/UtilPersonalTest.java
> +                () -> Assertions.assertFalse(UtilPersonal.validateEmail("emailtest.com"))
The class was removed attending our necessity.

2022-01-13 18:26 UTC, Robinson-Dev commented on src/test/java/com/learning/users/UserRepositoryTest.java
>          userRepository.create(user);
Yes. Now we have it. I created a controller layer do make this job. I'm not sure if I am in the right path. Please tell me.

Thank you

2022-01-14 20:11 UTC, ClaudenirFreitas requested changes

2022-01-14 20:11 UTC, ClaudenirFreitas commented on pom.xml
> +		<dependency>
There is a warning related to this lib.
```
[WARNING] The artifact org.hibernate:hibernate-validator:jar:7.0.1.Final has been relocated to org.hibernate.validator:hibernate-validator:jar:7.0.1.Final
```

Other dependencies improvements:
- [x] remove `org.jetbrains:org.jetbrains:23.0.0`
- [x] remove `junit:junit:4.13.0`

2022-01-14 20:11 UTC, ClaudenirFreitas commented on pom.xml
> +							<outputDirectory>coverage-report/</outputDirectory>
You can add this directory in the `.gitignore` file.

2022-01-14 20:11 UTC, ClaudenirFreitas commented on src/main/java/com/learning/users/Controller/UserController.java
> +            violations.forEach(userConstraintViolation -> System.out.println(userConstraintViolation.getMessage()));
Well, it's not a good idea to fail silently. If we have errors here, we need to throws them using Exception.  
I found this [interesting article](http://tutorials.jenkov.com/java-exception-handling/index.html) that will help to understand this topic. Using the Exception approach, this method can be void too.

2022-01-14 20:11 UTC, ClaudenirFreitas commented on src/main/java/com/learning/users/model/User.java
> +    @Size(min = 3, max = 50, message = "Name has to have between 3 and 50 characters.")
I believe we're able to create an user without `name`. It's necessary to check some annotations.

2022-01-14 20:11 UTC, ClaudenirFreitas commented on src/main/java/com/learning/users/model/User.java
> -    public int getId() {
Could you format the file? Because this piece of code is not using the Java pattern.
```
public int getId() { return id; }
```
The previous one was correct.
```
public int getId() { 
    return id; 
}
```

2022-01-14 20:11 UTC, ClaudenirFreitas commented on src/test/java/com/learning/users/UserRepositoryTest.java
> +        Assertions.assertNotNull(user);
`shouldCreateUser` method is not creating an user, right? `user` variable is an instance of _User_ but we don't have interactions to `UserRepository`.  
[This interesting video](https://www.youtube.com/watch?v=Og9T0OgIuPM) can be useful to understand more about tests.

2022-01-14 20:11 UTC, ClaudenirFreitas commented on src/test/java/com/learning/users/UserRepositoryTest.java
>          userRepository.create(user);
You need to move this one to `UserRepository` because this is the layer responsible for validating data when we're inserting them, ok?

2022-02-11 00:25 UTC, Robinson-Dev commented
Claudenir,  modifications were implemented. Could you check if it is in accord as expected?

Thank you

2022-03-05 03:04 UTC, Robinson-Dev commented on pom.xml
> +		<dependency>
I'm closing this because the action request was executed previously

2022-03-05 03:05 UTC, Robinson-Dev commented on src/main/java/com/learning/users/Controller/UserController.java
> +            violations.forEach(userConstraintViolation -> System.out.println(userConstraintViolation.getMessage()));
Mistake corrected.

2022-03-13 21:02 UTC, ClaudenirFreitas approved these changes
Ready to merge man!

2022-03-13 21:02 UTC, ClaudenirFreitas commented on pom.xml
> +							<outputDirectory>coverage-report/</outputDirectory>
@Robinson-Dev could you add `coverage-report/` folder in the `.gitignore` file?

2022-03-20 21:44 UTC, merged

2022-03-20 21:48 UTC, Robinson-Dev commented
All right. I merged into develop.

Thank you

On Sun, 13 Mar 2022 at 21:02, Claudenir Freitas ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Ready to merge man!
> ------------------------------
>
> In pom.xml:
>
> > @@ -88,7 +93,7 @@
>  							<goal>report</goal>
>  						</goals>
>  						<configuration>
> -							<outputDirectory>/coverage-report/</outputDirectory>
> +							<outputDirectory>coverage-report/</outputDirectory>
>
> @Robinson-Dev could you add coverage-report/ folder in the .gitignore
> file?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>