Feature/edit user
Robinson-Dev/users pull request #22
Opened 2022-02-12 01:27 UTC by Robinson-Dev

Claudenir, the implementation for user edition is done. When possible, please, ;et me know what is needed beyond what I have done.

Thank you

2022-02-12 02:36 UTC, Robinson-Dev commented
Please, do not consider this pull-request for now. I pushed it however I forgot to implement the UpdatedAt attribute.

2022-02-17 19:34 UTC, Robinson-Dev commented
Hello my manager. It's available right now. 

Thank you

2022-03-13 21:17 UTC, ClaudenirFreitas commented on src/main/java/com/learning/users/repository/UserRepositoryInMemory.java
> +        mapStorage.replace(user.getEmail(), user);
We need to check if the user id is the same, correct? Otherwise, we will override the user,

2022-03-13 21:17 UTC, ClaudenirFreitas commented on src/main/java/com/learning/users/repository/UserRepositoryInMemory.java
> +        Map<String, LocalDateTime> storageUserUpdated = new HashMap<>();
This `storageUserUpdated` is using a method scope, I didn't undertstand the idea here. Could you explain it, please?

2022-03-13 21:30 UTC, ClaudenirFreitas requested changes
I've just added some comments, could you check them please?

2022-03-20 21:58 UTC, Robinson-Dev commented on src/main/java/com/learning/users/repository/UserRepositoryInMemory.java
> +        Map<String, LocalDateTime> storageUserUpdated = new HashMap<>();
So, I used StorageUserUpdated to store separately, when the data user was updated. Did you get me?

2022-03-22 15:07 UTC, Robinson-Dev commented on src/main/java/com/learning/users/repository/UserRepositoryInMemory.java
> +        mapStorage.replace(user.getEmail(), user);
Got it. 
I made some adjustment related with this issue. In my mind that was the way I should cope with problem looking for not override it. If I did not follow you, please, feel free to correct me.

Thanks

2022-03-24 01:43 UTC, Robinson-Dev commented on src/main/java/com/learning/users/repository/UserRepositoryInMemory.java
> +        Map<String, LocalDateTime> storageUserUpdated = new HashMap<>();
Based on the next pull request where you asked to create a new attribute to store the deletion user date I understood I must do the same to updatedAt.

2022-04-10 02:53 UTC, merged